#ifndef BTSTACK_CONFIG_H
#define BTSTACK_CONFIG_H

#define HAVE_EMBEDDED_TIME_MS
#define HCI_ACL_PAYLOAD_SIZE 200
#define HCI_OUTGOING_PRE_BUFFER_SIZE 4
#define HCI_ACL_CHUNK_SIZE_ALIGNMENT 4
#define MAX_NR_HIDS_CONNECTIONS 2
#define MAX_NR_L2CAP_SERVICES 4
#define MAX_NR_L2CAP_CHANNELS 8
#define MAX_NR_RFCOMM_MULTIPLEXERS 0
#define MAX_NR_RFCOMM_SERVICES 0
#define MAX_NR_RFCOMM_CHANNELS 0
#define MAX_NR_BTSTACK_LINK_KEY_DB_MEMORY_ENTRIES 4
#define MAX_NR_HCI_CONNECTIONS 2
#define NVM_NUM_LINK_KEYS 4
#define ENABLE_HID_DEVICE
#define ENABLE_LE_PERIPHERAL
#define HAVE_MALLOC
#define MAX_NR_LE_DEVICE_DB_ENTRIES 4
#define NVM_NUM_DEVICE_DB_ENTRIES 4
#define ENABLE_LE_SECURE_CONNECTIONS
#define ENABLE_SDP_DES_DUMP
#define ENABLE_PRINTF_HEXDUMP
#undef ENABLE_LOG_INFO
#undef ENABLE_LOG_DEBUG

#endif // BTSTACK_CONFIG_H
