include_guard(GLOBAL)

set(GP2040_BOARD_RECORD_FIELDS
    PICO_BOARD
    PICO_PLATFORM
    GP2040_BOARD_LEGACY_PICO_BOARD
    PICO_DEFAULT_UART
    PICO_DEFAULT_UART_TX_PIN
    PICO_DEFAULT_UART_RX_PIN
    GP2040_BOARD_HEADER_DIR
    GP2040_BOARD_CMAKE_DIR
)

function(gp2040_load_board target directory prefix)
    if(NOT target MATCHES "^[A-Za-z0-9][A-Za-z0-9_.-]*$")
        message(FATAL_ERROR "Invalid GP2040 target ID '${target}'. Use a registered target name.")
    endif()
    file(REAL_PATH "${directory}" directory)
    set(record "${directory}/${target}.cmake")
    if(NOT EXISTS "${record}" OR NOT EXISTS "${directory}/BoardConfig.h")
        message(FATAL_ERROR "Incomplete GP2040 target '${target}' in '${directory}': ${target}.cmake and BoardConfig.h are required.")
    endif()
    foreach(field IN LISTS GP2040_BOARD_RECORD_FIELDS)
        set(${field} "")
    endforeach()
    include("${record}")
    if(NOT PICO_BOARD MATCHES "^[A-Za-z0-9_]+$")
        message(FATAL_ERROR "Target record '${record}' must declare an explicit PICO_BOARD hardware mapping.")
    endif()
    foreach(kind HEADER CMAKE)
        if(GP2040_BOARD_${kind}_DIR)
            file(REAL_PATH "${GP2040_BOARD_${kind}_DIR}" resolved_directory BASE_DIRECTORY "${directory}")
            if(kind STREQUAL "HEADER")
                set(extension h)
            else()
                set(extension cmake)
            endif()
            if(NOT EXISTS "${resolved_directory}/${PICO_BOARD}.${extension}")
                message(FATAL_ERROR "Target '${target}' requires '${resolved_directory}/${PICO_BOARD}.${extension}' (record: '${record}').")
            endif()
            set(GP2040_BOARD_${kind}_DIR "${resolved_directory}")
        endif()
    endforeach()
    foreach(field IN LISTS GP2040_BOARD_RECORD_FIELDS)
        set(${prefix}_${field} "${${field}}" PARENT_SCOPE)
    endforeach()
    set(${prefix}_DIRECTORY "${directory}" PARENT_SCOPE)
endfunction()

function(gp2040_board_roots output)
    set(roots "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../configs")
    if(DEFINED GP2040_BOARD_DIRS)
        list(APPEND roots ${GP2040_BOARD_DIRS})
    elseif(DEFINED ENV{GP2040_BOARD_DIRS})
        list(APPEND roots $ENV{GP2040_BOARD_DIRS})
    endif()
    set(normalized_roots "")
    foreach(root IN LISTS roots)
        file(REAL_PATH "${root}" root BASE_DIRECTORY "${CMAKE_SOURCE_DIR}")
        if(NOT IS_DIRECTORY "${root}")
            message(FATAL_ERROR "GP2040_BOARD_DIRS entry does not exist: '${root}'.")
        endif()
        list(APPEND normalized_roots "${root}")
    endforeach()
    list(REMOVE_DUPLICATES normalized_roots)
    set(${output} "${normalized_roots}" PARENT_SCOPE)
endfunction()

function(gp2040_find_boards output)
    gp2040_board_roots(roots)
    set(targets "")
    foreach(root IN LISTS roots)
        file(GLOB children LIST_DIRECTORIES TRUE "${root}/*")
        foreach(directory IN LISTS children)
            if(NOT IS_DIRECTORY "${directory}")
                continue()
            endif()
            file(GLOB contents "${directory}/*")
            if(NOT contents)
                continue()
            endif()
            get_filename_component(target "${directory}" NAME)
            if(target IN_LIST targets)
                message(FATAL_ERROR "Duplicate GP2040 target '${target}' in '${directory}'. Target IDs must be unique across GP2040_BOARD_DIRS and in-tree configs.")
            endif()
            gp2040_load_board("${target}" "${directory}" record)
            list(APPEND targets "${target}")
            set(GP2040_TARGET_${target}_DIRECTORY "${directory}" PARENT_SCOPE)
        endforeach()
    endforeach()
    list(SORT targets)
    set(${output} "${targets}" PARENT_SCOPE)
endfunction()

function(gp2040_json_string value output)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()