cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/GP2040BoardRegistry.cmake")

gp2040_find_boards(targets)
if(DEFINED GP2040_BOARD AND NOT GP2040_BOARD STREQUAL "" AND NOT GP2040_BOARD STREQUAL "all")
    if(NOT GP2040_BOARD IN_LIST targets)
        message(FATAL_ERROR "Unknown GP2040_BOARD '${GP2040_BOARD}'. Registered targets: ${targets}")
    endif()
    set(targets "${GP2040_BOARD}")
endif()
set(result "[]")
set(index 0)
foreach(target IN LISTS targets)
    gp2040_json_string("${target}" value)
    string(JSON result SET "${result}" ${index} "${value}")
    math(EXPR index "${index} + 1")
endforeach()
if(DEFINED GP2040_BOARD_OUTPUT)
    file(WRITE "${GP2040_BOARD_OUTPUT}" "${result}\n")
else()
    message("${result}")
endif()