include("${CMAKE_CURRENT_LIST_DIR}/GP2040BoardRegistry.cmake")

if(NOT DEFINED GP2040_BOARD_DIRS)
    set(GP2040_BOARD_DIRS "$ENV{GP2040_BOARD_DIRS}" CACHE STRING "Additional GP2040 target package roots")
endif()

foreach(selector GP2040_BOARD GP2040_BOARDCONFIG PICO_BOARD PICO_PLATFORM)
    if(DEFINED ${selector})
        set(GP2040_INPUT_${selector} "${${selector}}")
    elseif(DEFINED ENV{${selector}})
        set(GP2040_INPUT_${selector} "$ENV{${selector}}")
    else()
        set(GP2040_INPUT_${selector} "")
    endif()
endforeach()

if(DEFINED GP2040_BOARD OR DEFINED ENV{GP2040_BOARD})
    set(selected_target "${GP2040_INPUT_GP2040_BOARD}")
elseif(DEFINED GP2040_BOARDCONFIG OR DEFINED ENV{GP2040_BOARDCONFIG})
    set(selected_target "${GP2040_INPUT_GP2040_BOARDCONFIG}")
else()
    set(selected_target Pico)
    message(STATUS "No GP2040 board selector supplied; defaulting to Pico.")
endif()

gp2040_find_boards(registered_targets)
if(NOT selected_target IN_LIST registered_targets)
    message(FATAL_ERROR "Unknown GP2040_BOARD '${selected_target}'. Use a registered target: ${registered_targets}. SDK-only names require a complete target record.")
endif()
gp2040_load_board("${selected_target}" "${GP2040_TARGET_${selected_target}_DIRECTORY}" GP2040_RECORD)
file(SHA256 "${GP2040_RECORD_DIRECTORY}/${selected_target}.cmake" record_hash)
set(selection_identity "${selected_target}|${GP2040_RECORD_DIRECTORY}|${record_hash}")
if(DEFINED GP2040_PREVIOUS_SELECTION AND NOT GP2040_PREVIOUS_SELECTION STREQUAL selection_identity)
    message(FATAL_ERROR "GP2040 target or hardware record changed in this build tree. Reconfigure with cmake -G Ninja -S . -B build --fresh -DGP2040_BOARD=${selected_target}.")
endif()

if(NOT GP2040_INPUT_GP2040_BOARDCONFIG STREQUAL "")
    if(NOT GP2040_INPUT_GP2040_BOARDCONFIG STREQUAL selected_target)
        message(FATAL_ERROR "Conflicting GP2040_BOARDCONFIG='${GP2040_INPUT_GP2040_BOARDCONFIG}' and GP2040_BOARD='${selected_target}'. Remove the legacy selector, including inherited environment values.")
    endif()
    message(DEPRECATION "GP2040_BOARDCONFIG is a deprecated board selector. Use -DGP2040_BOARD=${selected_target}.")
endif()
if(NOT GP2040_INPUT_PICO_BOARD STREQUAL "")
    if(NOT GP2040_INPUT_PICO_BOARD STREQUAL GP2040_RECORD_PICO_BOARD
        AND NOT GP2040_INPUT_PICO_BOARD STREQUAL GP2040_RECORD_GP2040_BOARD_LEGACY_PICO_BOARD)
        message(FATAL_ERROR "Conflicting PICO_BOARD='${GP2040_INPUT_PICO_BOARD}': '${selected_target}' requires '${GP2040_RECORD_PICO_BOARD}'. Remove the legacy value and configure with --fresh.")
    endif()
    if(NOT DEFINED GP2040_PREVIOUS_SELECTION)
        message(DEPRECATION "PICO_BOARD is derived from GP2040_BOARD; remove the redundant hardware selector.")
    endif()
endif()

set(GP2040_BOARD "${selected_target}" CACHE STRING "Registered GP2040 controller target" FORCE)
set_property(CACHE GP2040_BOARD PROPERTY STRINGS ${registered_targets})
set(GP2040_BOARDCONFIG "${selected_target}")
set(GP2040_BOARD_CONFIG_DIR "${GP2040_RECORD_DIRECTORY}")
set(PICO_BOARD "${GP2040_RECORD_PICO_BOARD}" CACHE STRING "Resolved SDK board" FORCE)
if(NOT GP2040_INPUT_PICO_PLATFORM STREQUAL "")
    set(PICO_PLATFORM "${GP2040_INPUT_PICO_PLATFORM}")
endif()

foreach(field PICO_DEFAULT_UART PICO_DEFAULT_UART_TX_PIN PICO_DEFAULT_UART_RX_PIN)
    if(NOT GP2040_RECORD_${field} STREQUAL "")
        if(DEFINED ${field} AND NOT "${${field}}" STREQUAL "${GP2040_RECORD_${field}}")
            message(FATAL_ERROR "${field} conflicts with the hardware policy for '${GP2040_BOARD}'. Use --fresh and remove the override.")
        endif()
        set(${field} "${GP2040_RECORD_${field}}")
    endif()
endforeach()

foreach(kind HEADER CMAKE)
    set(search_paths "${PICO_BOARD_${kind}_DIRS}")
    if(DEFINED ENV{PICO_BOARD_${kind}_DIRS})
        list(APPEND search_paths $ENV{PICO_BOARD_${kind}_DIRS})
    endif()
    if(GP2040_RECORD_GP2040_BOARD_${kind}_DIR)
        list(PREPEND search_paths "${GP2040_RECORD_GP2040_BOARD_${kind}_DIR}")
    endif()
    list(REMOVE_DUPLICATES search_paths)
    set(PICO_BOARD_${kind}_DIRS "${search_paths}")
    if(DEFINED ENV{PICO_BOARD_${kind}_DIRS})
        set(ENV{PICO_BOARD_${kind}_DIRS} "${search_paths}")
    endif()
endforeach()

function(gp2040_validate_sdk_board)
    set(sdk_header "${PICO_SDK_PATH}/src/boards/include/boards/${PICO_BOARD}.h")
    if(GP2040_RECORD_GP2040_BOARD_HEADER_DIR)
        if(EXISTS "${sdk_header}")
            message(FATAL_ERROR "Custom target '${GP2040_BOARD}' shadows SDK board '${PICO_BOARD}'. Use a distinctive custom header name.")
        endif()
        set(expected_header "${GP2040_RECORD_GP2040_BOARD_HEADER_DIR}/${PICO_BOARD}.h")
    else()
        set(expected_header "${sdk_header}")
    endif()
    if(NOT EXISTS "${expected_header}" OR NOT EXISTS "${PICO_BOARD_HEADER_FILE}")
        message(FATAL_ERROR "Target '${GP2040_BOARD}' requires SDK hardware header '${expected_header}', but the SDK resolved '${PICO_BOARD_HEADER_FILE}'.")
    endif()
    file(REAL_PATH "${expected_header}" expected_header)
    file(REAL_PATH "${PICO_BOARD_HEADER_FILE}" actual_header)
    if(NOT expected_header STREQUAL actual_header)
        message(FATAL_ERROR "Hardware header shadowing for '${GP2040_BOARD}': expected '${expected_header}', SDK selected '${actual_header}'. Check PICO_BOARD_HEADER_DIRS and inherited environment values.")
    endif()
    if(NOT PICO_PLATFORM STREQUAL "rp2040" AND NOT PICO_PLATFORM STREQUAL "rp2350-arm-s")
        message(FATAL_ERROR "Unsupported GP2040 platform '${PICO_PLATFORM}'; registered firmware supports rp2040 or rp2350-arm-s.")
    endif()
    if(GP2040_RECORD_PICO_PLATFORM AND NOT GP2040_RECORD_PICO_PLATFORM STREQUAL PICO_PLATFORM)
        message(FATAL_ERROR "Target '${GP2040_BOARD}' expects '${GP2040_RECORD_PICO_PLATFORM}', SDK resolved '${PICO_PLATFORM}'.")
    endif()
    set(GP2040_PREVIOUS_SELECTION "${selection_identity}" CACHE INTERNAL "Resolved target and hardware record" FORCE)
    message(STATUS "GP2040 target: ${GP2040_BOARD}")
    message(STATUS "GP2040 firmware config: ${GP2040_BOARD_CONFIG_DIR}/BoardConfig.h")
    message(STATUS "GP2040 hardware header: ${actual_header}")
    message(STATUS "GP2040 SDK board/platform: ${PICO_BOARD}/${PICO_PLATFORM}")
endfunction()