function(gp2040_add_board_validation target)
    math(EXPR GP2040_RESOLVED_FLASH_BYTES "${PICO_FLASH_SIZE_BYTES}")
    if(PICO_PLATFORM STREQUAL "rp2350-arm-s")
        set(GP2040_RESOLVED_RP2350 1)
    else()
        set(GP2040_RESOLVED_RP2350 0)
    endif()
    if(PICO_CYW43_SUPPORTED)
        set(GP2040_RESOLVED_WIRELESS 1)
    else()
        set(GP2040_RESOLVED_WIRELESS 0)
    endif()
    foreach(capability GPIO ADC ADC_BASE FLASH)
        set(GP2040_EXPECT_${capability} 0)
    endforeach()
    set(GP2040_EXPECT_WIRELESS -1)
    if(GP2040_BOARD_TEST_EXPECTATIONS)
        include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/board-expectations.cmake")
    endif()
    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/BoardCapabilities.cpp.in"
        "${CMAKE_BINARY_DIR}/generated/board_capabilities.cpp" @ONLY)
    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/board_storage.ld.in"
        "${CMAKE_BINARY_DIR}/generated/board_storage.ld" @ONLY)
    target_sources(${target} PRIVATE "${CMAKE_BINARY_DIR}/generated/board_capabilities.cpp")
    target_link_options(${target} PRIVATE "LINKER:-T,${CMAKE_BINARY_DIR}/generated/board_storage.ld")
    set_property(TARGET ${target} APPEND PROPERTY LINK_DEPENDS "${CMAKE_BINARY_DIR}/generated/board_storage.ld")
    if(PICO_CYW43_SUPPORTED)
        find_package(Python3 REQUIRED COMPONENTS Interpreter)
        execute_process(COMMAND "${Python3_EXECUTABLE}" -c "from Cryptodome.Hash import CMAC; from Cryptodome.Cipher import AES"
            RESULT_VARIABLE crypto_result OUTPUT_QUIET ERROR_QUIET)
        if(NOT crypto_result EQUAL 0)
            message(FATAL_ERROR "BLE GATT generation requires pycryptodomex in '${Python3_EXECUTABLE}'. Install it with that interpreter's -m pip install pycryptodomex; random database hashes are not accepted.")
        endif()
    endif()
    message(STATUS "GP2040 CYW43: ${GP2040_RESOLVED_WIRELESS}; effective flash: ${GP2040_RESOLVED_FLASH_BYTES} bytes")
    message(STATUS "GP2040 EEPROM: 0x101F8000 + 0x8000; compiler and linker bounds checks enabled")
endfunction()