cmake_minimum_required(VERSION 3.24)
get_filename_component(source_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

if(GP2040_TEST_PROBE)
    include("${source_root}/modules/SelectBoard.cmake")
    if(DEFINED GP2040_TEST_TARGET AND NOT GP2040_BOARD STREQUAL GP2040_TEST_TARGET)
        message(FATAL_ERROR "Expected target '${GP2040_TEST_TARGET}', got '${GP2040_BOARD}'.")
    endif()
    if(DEFINED GP2040_TEST_BOARD AND NOT PICO_BOARD STREQUAL GP2040_TEST_BOARD)
        message(FATAL_ERROR "Expected SDK board '${GP2040_TEST_BOARD}', got '${PICO_BOARD}'.")
    endif()
    if(DEFINED GP2040_TEST_CONFIG_DIR AND NOT GP2040_BOARD_CONFIG_DIR STREQUAL GP2040_TEST_CONFIG_DIR)
        message(FATAL_ERROR "Wrong firmware defaults directory: '${GP2040_BOARD_CONFIG_DIR}'.")
    endif()
    if(GP2040_TEST_VALIDATE_HEADER)
        gp2040_validate_sdk_board()
    endif()
    return()
endif()

set(test_root "${source_root}/build/board-selection-tests")
file(MAKE_DIRECTORY "${test_root}/working directory" "${test_root}/packages with spaces")
file(COPY "${CMAKE_CURRENT_LIST_DIR}/fixtures/boards/CustomPico" DESTINATION "${test_root}/packages with spaces")
file(WRITE "${test_root}/project/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.24)
include("${GP2040_TEST_SOURCE_ROOT}/modules/SelectBoard.cmake")
include("${GP2040_TEST_SOURCE_ROOT}/pico_sdk_import.cmake")
gp2040_validate_sdk_board()
if(DEFINED GP2040_TEST_BOARD AND NOT PICO_BOARD STREQUAL GP2040_TEST_BOARD)
    message(FATAL_ERROR "Wrong SDK board: '${PICO_BOARD}'.")
endif()
if(DEFINED GP2040_TEST_CONFIG_DIR AND NOT GP2040_BOARD_CONFIG_DIR STREQUAL GP2040_TEST_CONFIG_DIR)
    message(FATAL_ERROR "Wrong firmware defaults directory: '${GP2040_BOARD_CONFIG_DIR}'.")
endif()
project(BoardSelectionProbe NONE)
]=])

function(check_selection name)
    cmake_parse_arguments(TEST "REAL_SDK;REUSE" "TARGET;BOARD;ERROR;TREE" "ARGS;ENV" ${ARGN})
    set(clean_environment "")
    foreach(variable GP2040_BOARD GP2040_BOARDCONFIG GP2040_BOARD_DIRS PICO_BOARD PICO_PLATFORM PICO_BOARD_HEADER_DIRS PICO_BOARD_CMAKE_DIRS)
        list(APPEND clean_environment "--unset=${variable}")
    endforeach()
    set(arguments -DGP2040_TEST_PROBE=ON)
    if(TEST_TARGET)
        list(APPEND arguments "-DGP2040_TEST_TARGET=${TEST_TARGET}")
    endif()
    if(TEST_BOARD)
        list(APPEND arguments "-DGP2040_TEST_BOARD=${TEST_BOARD}")
    endif()
    if(TEST_REAL_SDK)
        if(NOT TEST_TREE)
            set(TEST_TREE "${name}")
        endif()
        set(mode_args -S "${test_root}/project" -B "${test_root}/sdk-builds/${TEST_TREE}")
        if(NOT TEST_REUSE)
            list(APPEND mode_args --fresh)
        endif()
        list(APPEND arguments "-DGP2040_TEST_SOURCE_ROOT=${source_root}" "-DPICO_SDK_PATH=${test_sdk}")
    else()
        set(mode_args -P "${CMAKE_CURRENT_FUNCTION_LIST_FILE}")
    endif()
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E env ${clean_environment} ${TEST_ENV}
            "${CMAKE_COMMAND}" -G Ninja ${arguments} ${TEST_ARGS} ${mode_args}
        WORKING_DIRECTORY "${test_root}/working directory"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors
    )
    if(TEST_ERROR)
        if(result EQUAL 0 OR NOT "${output}${errors}" MATCHES "${TEST_ERROR}")
            message(FATAL_ERROR "${name}: expected failure '${TEST_ERROR}', got ${result}:\n${output}${errors}")
        endif()
    elseif(NOT result EQUAL 0)
        message(FATAL_ERROR "${name}: failed (${result}):\n${output}${errors}")
    endif()
    message(STATUS "PASS: ${name}")
endfunction()

check_selection(default TARGET Pico BOARD pico)
check_selection(public_selector TARGET Pico2W BOARD pico2_w ARGS -DGP2040_BOARD=Pico2W)
check_selection(legacy_alias TARGET PicoW BOARD pico_w ARGS -DGP2040_BOARDCONFIG=PicoW)
check_selection(matching_legacy TARGET PicoW BOARD pico_w ARGS -DGP2040_BOARD=PicoW -DGP2040_BOARDCONFIG=PicoW -DPICO_BOARD=pico_w)
check_selection(pimoroni_legacy TARGET PimoroniPicoLipo2XLW BOARD gp2040_pimoroni_lipo2xlw ARGS -DGP2040_BOARDCONFIG=PimoroniPicoLipo2XLW -DPICO_BOARD=pico2_w)
check_selection(environment_selector TARGET PicoW BOARD pico_w ENV GP2040_BOARD=PicoW)
check_selection(cache_over_environment TARGET Pico BOARD pico ARGS -DGP2040_BOARD=Pico ENV GP2040_BOARD=PicoW)
check_selection(alias_cache_over_environment TARGET Pico BOARD pico ARGS -DGP2040_BOARDCONFIG=Pico ENV GP2040_BOARDCONFIG=PicoW)
check_selection(hardware_cache_over_environment TARGET Pico BOARD pico ARGS -DGP2040_BOARD=Pico -DPICO_BOARD=pico ENV PICO_BOARD=pico_w)
check_selection(unknown ERROR "Unknown GP2040_BOARD" ARGS -DGP2040_BOARD=UnknownController)
check_selection(empty_selector ERROR "Unknown GP2040_BOARD" ARGS -DGP2040_BOARD=)
check_selection(empty_legacy_selector ERROR "Unknown GP2040_BOARD" ARGS -DGP2040_BOARDCONFIG=)
check_selection(unregistered_sdk_board ERROR "SDK-only names" ARGS -DGP2040_BOARD=pico2)
check_selection(conflicting_alias ERROR "Conflicting GP2040_BOARDCONFIG" ARGS -DGP2040_BOARD=Pico2 -DGP2040_BOARDCONFIG=Pico)
check_selection(conflicting_hardware ERROR "Conflicting PICO_BOARD" ARGS -DGP2040_BOARD=Pico2 -DPICO_BOARD=pico)
check_selection(conflicting_environment ERROR "Conflicting PICO_BOARD" ARGS -DGP2040_BOARD=Pico2 ENV PICO_BOARD=pico)
check_selection(stale_target ERROR "--fresh" ARGS -DGP2040_BOARD=Pico2 -DGP2040_PREVIOUS_SELECTION=previous)
check_selection(missing_root ERROR "does not exist" ARGS "-DGP2040_BOARD_DIRS=${test_root}/absent")
check_selection(external_spaces TARGET CustomPico BOARD gp2040_test_pico ARGS -DGP2040_BOARD=CustomPico "-DGP2040_BOARD_DIRS=${test_root}/packages with spaces" "-DGP2040_TEST_CONFIG_DIR=${test_root}/packages with spaces/CustomPico")
check_selection(external_environment TARGET CustomPico BOARD gp2040_test_pico ENV GP2040_BOARD=CustomPico "GP2040_BOARD_DIRS=${test_root}/packages with spaces")

file(MAKE_DIRECTORY "${test_root}/duplicate/Pico")
file(WRITE "${test_root}/duplicate/Pico/Pico.cmake" "set(PICO_BOARD pico)\n")
file(WRITE "${test_root}/duplicate/Pico/BoardConfig.h" "\n")
check_selection(duplicate ERROR "Duplicate GP2040 target" ARGS "-DGP2040_BOARD_DIRS=${test_root}/duplicate")

file(MAKE_DIRECTORY "${test_root}/incomplete/Incomplete")
file(WRITE "${test_root}/incomplete/Incomplete/Incomplete.cmake" "set(PICO_BOARD pico)\n")
check_selection(missing_defaults ERROR "Incomplete GP2040 target" ARGS "-DGP2040_BOARD_DIRS=${test_root}/incomplete")

file(MAKE_DIRECTORY "${test_root}/missing-record/MissingRecord")
file(WRITE "${test_root}/missing-record/MissingRecord/BoardConfig.h" "\n")
check_selection(missing_record ERROR "Incomplete GP2040 target" ARGS "-DGP2040_BOARD_DIRS=${test_root}/missing-record")

file(MAKE_DIRECTORY "${test_root}/missing-header/MissingHeader")
file(WRITE "${test_root}/missing-header/MissingHeader/MissingHeader.cmake" "set(PICO_BOARD missing_custom_header)\nset(GP2040_BOARD_HEADER_DIR hardware)\n")
file(WRITE "${test_root}/missing-header/MissingHeader/BoardConfig.h" "\n")
check_selection(missing_header ERROR "missing_custom_header.h" ARGS "-DGP2040_BOARD_DIRS=${test_root}/missing-header")

file(MAKE_DIRECTORY "${test_root}/no-mapping/NoMapping")
file(WRITE "${test_root}/no-mapping/NoMapping/NoMapping.cmake" "\n")
file(WRITE "${test_root}/no-mapping/NoMapping/BoardConfig.h" "\n")
check_selection(missing_mapping ERROR "explicit PICO_BOARD" ARGS "-DGP2040_BOARD_DIRS=${test_root}/no-mapping")

set(mock_sdk "${test_root}/sdk")
file(MAKE_DIRECTORY "${mock_sdk}/src/boards/include/boards")
file(WRITE "${mock_sdk}/src/boards/include/boards/pico.h" "\n")
file(WRITE "${test_root}/shadow.h" "\n")
check_selection(shadowed_sdk_header ERROR "Hardware header shadowing" ARGS -DGP2040_BOARD=Pico -DGP2040_TEST_VALIDATE_HEADER=ON "-DPICO_SDK_PATH=${mock_sdk}" "-DPICO_BOARD_HEADER_FILE=${test_root}/shadow.h" -DPICO_PLATFORM=rp2040)
check_selection(unsupported_platform ERROR "Unsupported GP2040 platform" ARGS -DGP2040_BOARD=Pico -DGP2040_TEST_VALIDATE_HEADER=ON "-DPICO_SDK_PATH=${mock_sdk}" "-DPICO_BOARD_HEADER_FILE=${mock_sdk}/src/boards/include/boards/pico.h" -DPICO_PLATFORM=rp2350-riscv)

file(MAKE_DIRECTORY "${test_root}/collision/Collision/hardware")
file(WRITE "${test_root}/collision/Collision/Collision.cmake" "set(PICO_BOARD pico)\nset(GP2040_BOARD_HEADER_DIR hardware)\n")
file(WRITE "${test_root}/collision/Collision/BoardConfig.h" "\n")
file(WRITE "${test_root}/collision/Collision/hardware/pico.h" "#include \"boards/pico.h\"\n")
check_selection(custom_sdk_collision ERROR "shadows SDK board" ARGS -DGP2040_BOARD=Collision "-DGP2040_BOARD_DIRS=${test_root}/collision" -DGP2040_TEST_VALIDATE_HEADER=ON "-DPICO_SDK_PATH=${mock_sdk}")

if(PICO_SDK_PATH)
    set(test_sdk "${PICO_SDK_PATH}")
else()
    set(test_sdk "$ENV{PICO_SDK_PATH}")
endif()
if(EXISTS "${test_sdk}/pico_sdk_init.cmake")
    check_selection(sdk_pico REAL_SDK TREE reused BOARD pico ARGS -DGP2040_BOARD=Pico)
    check_selection(sdk_reconfigure REAL_SDK REUSE TREE reused BOARD pico)
    check_selection(sdk_stale_target REAL_SDK REUSE TREE reused ERROR "--fresh" ARGS -DGP2040_BOARD=Pico2)
    check_selection(sdk_platform_conflict REAL_SDK ERROR "[Pp]latform" ARGS -DGP2040_BOARD=Pico -DPICO_PLATFORM=rp2350-arm-s)
    check_selection(sdk_external_spaces REAL_SDK BOARD gp2040_test_pico ARGS -DGP2040_BOARD=CustomPico "-DGP2040_BOARD_DIRS=${test_root}/packages with spaces" "-DGP2040_TEST_CONFIG_DIR=${test_root}/packages with spaces/CustomPico" ENV "PICO_BOARD_HEADER_DIRS=${test_root}/inherited headers")
    check_selection(sdk_environment_roots REAL_SDK TREE environment-roots BOARD gp2040_test_pico ARGS -DGP2040_BOARD=CustomPico ENV "GP2040_BOARD_DIRS=${test_root}/packages with spaces")
    check_selection(sdk_cached_roots REAL_SDK REUSE TREE environment-roots BOARD gp2040_test_pico)
    file(MAKE_DIRECTORY "${test_root}/shadowed headers")
    file(COPY "${test_sdk}/src/boards/include/boards/pico.h" DESTINATION "${test_root}/shadowed headers")
    check_selection(sdk_environment_shadow REAL_SDK ERROR "Hardware header shadowing" ARGS -DGP2040_BOARD=Pico ENV "PICO_BOARD_HEADER_DIRS=${test_root}/shadowed headers")
    check_selection(sdk_custom_collision REAL_SDK ERROR "shadows SDK board" ARGS -DGP2040_BOARD=Collision "-DGP2040_BOARD_DIRS=${test_root}/collision")
else()
    message(STATUS "SDK integration checks skipped; set PICO_SDK_PATH to run them.")
endif()

execute_process(COMMAND "${CMAKE_COMMAND}" -G Ninja "-DGP2040_BOARD_OUTPUT=${test_root}/boards.json" -P "${source_root}/modules/ListBoards.cmake" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Registry JSON generation failed.")
endif()
file(READ "${test_root}/boards.json" registry)
string(JSON count LENGTH "${registry}")
if(count LESS 57)
    message(FATAL_ERROR "Registry lost existing targets (${count}).")
endif()
message(STATUS "PASS: JSON registry contains ${count} targets")